name: NinjaEdit
main: com.ninja.NinjaEdit.NinjaEdit
version: 1.0.3
commands:
   /pos1:
      description: Set's a NinjaEdit pos
      usage: //pos1
   /pos2:
      description: Set's a NinjaEdit pos
      usage: //pos2
   /set:
      description: Set's marked position to a block
      usage: //set <id>
   /replace:
      description: Replaces blocks in selection
      usage: //replace <id> <id>
   /undo:
      description: Undo stuff
      usage: //undo
   /redo:
      description: Redo stuff
      usage: //redo
   /up:
      description: Go up.
      usage: //up <value> 
   /copy:
      description: copy your selection to your clipboard.
      usage: //copy
   /paste:
      description: paste your clipboard.
      usage: //paste
   /cut:
      description: cut the selection to your clipboard.
      usage: //cut
   /stack:
      description: stack your selection in a direction.
      usage: //stack <dir>